[tool.poetry]
name = "image-search"
version = "0.1.0"
description = ""
authors = ["Luis Miguel Serrano <luis.miguel.santos.serrano@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
